### ISSUE TITLE
NoClassDefFoundError when packing project in OmegaT 6.1.0

### ISSUE THREAD

**Issue by msoutopico** [briacp/plugin-omt-package#11]
## Preconditions

- Plugin version: `/home/souto/.omegat/plugins/plugin-omt-package-1.7.0.jar`

## Steps

- Open Project
- Go to Project > Pack project as OMT file...

## Results

- The OMT package is written but most of the contents are missing. 
- Error: 

```
Unable to read project file! 

---
java.lang.NoClassDefFoundError: org/apache/commons/lang/StringUtils
---
Version: OmegaT-6.1.0_0_0d9f75a57
Platform: Linux 6.1.33-1-lts
Java: 11.0.17 amd64
Memory: 904MiB total / 685MiB free / 12006MiB max
```

**Comment by briacp** [comment]
Fixed in [release 1.8.0](https://github.com/briacp/plugin-omt-package/releases/tag/v1.8.0), this release is only for OmegaT 6.1.0 and onwards.
