### ISSUE TITLE
Add property in config to remove mappings (to pack as offline project)

### ISSUE THREAD

**Issue by msoutopico** [briacp/plugin-omt-package#9]
### Request 

Add property `pack-as-offline-project` to the `omt-package-config.properties` file. 

If value is `true`, the following behaviour is expected: 

### Steps: 

1. A team project is open in OmegaT.
2. Project > Pack project as OMT file

### Results: 

1. The `omegat.project` file inside the OMT package does not have a `<repositories>` section. 
2. All files pulled from mapped repositories when the team project loads are included in the OMT package.
3. Additionally, if possible, any other ancillary git files are not included in the package (e.g. `.repositories` directory,  `.gitattributes` file, etc.)

### Example

This is an example of the section that should be removed: 

```xml
    <repositories>
      <repository type="git" url="&DOMAIN;/&THIS_REPO;.git">
      <!-- self -->
        <mapping local="/" repository="/" />
      </repository>
      <repository type="git" url="&DOMAIN;/pisa_2025ft_translation_common.git">
        <!-- source files -->
        <mapping local="source/01_QQS_N/" repository="source/01_QQS_N/" />
        <mapping local="source/01_QQS_N2/" repository="source/01_QQS_N2/" />
        <mapping local="omegat/filters.xml" repository="config/filters.xml" />
        <mapping local="omegat/okf_xml@oat.fprm" repository="config/okf_xml@oat.fprm" />
        <mapping local="omegat/okf_xml@qti.fprm" repository="config/okf_xml@qti.fprm" />
        <mapping local="omegat/segmentation.conf" repository="config/segmentation.conf" />
        <!-- language assets -->
        <mapping local="tm/auto/" repository="assets/&TARGET_LANG;/tm/prep/" />
        <mapping local="tm/auto/" repository="assets/&TARGET_LANG;/tm/auto/" />        
        <mapping local="tm/enforce/" repository="assets/&TARGET_LANG;/tm/enforce/" />
        <mapping local="glossary/validated/" repository="assets/&TARGET_LANG;/tb/" />
      </repository>
    </repositories>
```

**Comment by msoutopico** [comment]
Thanks, Briac. What shall I do to test this new feature? Do you need to release a new version (v. 1.6.5, I guess) of the plugin?

**Comment by briacp** [comment]
@msoutopico the release 1.7.0 is just out! 

https://github.com/briacp/plugin-omt-package/releases/tag/v1.7.0

**Comment by msoutopico** [comment]
@briacp I have now tested this new feature. If I add line `pack-as-offline-project=true` to the `omt-package-config.properties`, packing a team project results in an OMT package containing an `omegat.project` that does not have a ` <repositories>` node. That seems to work fine, thanks a lot! 

However, I can still see the hidden `.repositories` folder inside the OMT package. That folder can become quite big. Would it be possible to remove it too when packing with this new option?

**Comment by briacp** [comment]
@msoutopico The [1.7.1](https://github.com/briacp/plugin-omt-package/releases/tag/v1.7.1) release fixes that. If the offline option is set, the `.repositories`, `.svn` and `.git` repositories are always skipped.

(note that the `exclude-pattern` properties could also have been used to skip these directories)
